name: "QEMU"
description: "Builds a repository and run several tests with QEMU qmp"
inputs:
  time_before_tests:
    description: 'time_before_tests'
    required: true
    default: "1"
  kint:
    description: 'kint'
    required: true
    default: "0x01"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --time_before_tests=${{inputs.time_before_tests}} --kint=${{inputs.kint}}